more

diff --git a/.github/workflows/gradle_test.yml b/.github/workflows/gradle_test.yml
--- a/.github/workflows/gradle_test.yml
+++ b/.github/workflows/gradle_test.yml
@@ -16,11 +16,118 @@ on:
       - master
   workflow_dispatch:
 jobs:
-  # this test is a heavily modified version of the official gradle test
-  # so that it runs each test in parallel and then aggregates the results
-  # all in github actions
+  # this test is a heavily modified version of the official gradle test so that it runs each test in parallel and then
+  # aggregates the results all in github actions
+  saveGradleCacheAndDameon:
+    # this part caches gradle, gradle wrapper, gradle cache, and the gradle daemon so that it doesn't have to download
+    # them for each job
+    runs-on: ubuntu-latest
+    steps:
+        - uses: actions/checkout@v2
+        - uses: actions/setup-java@v1
+          with:
+            java-version: 11
+            distribution: 'temurin'
+        - name: Setup Gradle
+          uses: gradle/gradle-build-action@v2
+          with:
+            arguments: wrapper
+  classes:
+    needs: saveGradleCacheAndDameon
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-java@v1
+        with:
+          java-version: 11
+          distribution: 'temurin'
+      - name: Gradle Classes
+        uses: gradle/gradle-build-action@v2
+        with:
+          arguments: classes
+      - name: Upload classes
+        uses: actions/upload-artifact@v2
+        with:
+          name: classes
+          path:
+            build/classes/java/main
+            build/classes/kotlin/main
+  testClasses:
+    needs:
+      saveGradleCacheAndDameon
+      classes
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-java@v1
+        with:
+          java-version: 11
+          distribution: 'temurin'
+      - name: download classes
+        uses: actions/download-artifact@v2
+        with:
+          name: classes
+          path:
+            build/classes/java/main
+            build/classes/java/test
+      - name: Gradle Test Classes
+        uses: gradle/gradle-build-action@v2
+        with:
+          arguments: testClasses
+      - name: Upload test classes
+        uses: actions/upload-artifact@v2
+        with:
+          name: testClasses
+          path:
+            - build/classes/java/test
+            - build/classes/kotlin/test
+  javadoc:
+    needs:
+      saveGradleCacheAndDameon
+      classes
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-java@v1
+        with:
+          java-version: 11
+          distribution: 'temurin'
+      - name: download classes
+        uses: actions/download-artifact@v2
+        with:
+          name: classes
+          path:
+            build/classes/java/main
+            build/classes/java/test
+      - name: Gradle Javadoc
+        uses: gradle/gradle-build-action@v2
+        with:
+          arguments: javadoc
+      - name: Upload javadoc
+        uses: actions/upload-artifact@v2
+        with:
+          name: javadoc
+          path: build/docs/javadoc
+  javadocToGitHubPages:
+    needs:
+      javadoc
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - name: download javadoc
+        uses: actions/download-artifact@v2
+        with:
+          name: javadoc
+          path: build/docs/javadoc
+      - name: upload to gh-pages branch
+        uses: peaceiris/actions-gh-pages@v3
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          publish_dir: build/docs/javadoc
+          publish_branch: gh-pages
   get-tests:
     runs-on: ubuntu-latest
+    needs: saveGradleCacheAndDameon
     steps:
       - uses: actions/checkout@v3 # checkout the repo
       - name: Set up JDK 11 # set up java 11
@@ -31,7 +138,9 @@ jobs:
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew # make gradlew executable
       - name: Get tests
-        run: ./gradlew getTests # run the getTests task which should generate a file called tests.txt
+        uses: gradle/gradle-build-action@v2
+        with:
+          arguments: getTests
       - name: Upload tests
         # upload the tests.txt file as an artifact (which is a file that can be downloaded)
         uses: actions/upload-artifact@v3
@@ -47,18 +156,10 @@ jobs:
     outputs:
       tests: ${{ steps.testid.outputs.tests }}
 
-
-  out:
-    needs: get-tests
-    runs-on: ubuntu-latest
-    steps:
-      # print the output of the previous job
-        - name: Print output
-          run: echo ${{ needs.get-tests.outputs.tests }}
-        - name: Print output
-          run: echo ${{ fromJSON(needs.get-tests.outputs.tests) }}
   test:
-    needs: get-tests
+    needs:
+      get-tests
+      testClasses
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -73,7 +174,32 @@ jobs:
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
       - name: Run tests
-        run: ./gradlew test --tests ${{ matrix.test }}
+        # if it fails, this task should fail
+        # if it skips, this task should skip
+        # if it passes, this task should pass
 
+        run: ./gradlew test --tests ${{ matrix.test }} --continue
+        continue-on-error: true
+      - name: handle errors, skips, and passes
+        # if the test failed, we want the job to fail
+        # if the test skipped, we want the job to skip
+        # if the test passed, we want the job to pass
+        run: |
+          if grep -q "FAILED" build/test-results/test/TEST-*.xml; then
+            echo "::error::Test failed" # ::error:: is a special string that makes the job fail
+            exit 1 # exit with a non-zero exit code
+          elif grep -q "SKIPPED" build/test-results/test/TEST-*.xml; then
+            echo "::warning::Test skipped" # ::warning:: is a special string that doesnt make the job skip but makes it 
+              # yellow
+            exit 78 # exit code for skipped
+          else
+            echo "::success::Test passed"
+            exit 0 # exit with a zero exit code
+          fi
+      - name: Upload test results
+        uses: actions/upload-artifact@v3
+        with:
+          name: test-results
+          path: build/test-results
 permissions:
   contents: read
